name: fyx
description: Fyx for Nyx.cz

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 11.1.0+159

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.3.0

dependencies:
  async: ^2.8.2
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  chewie: ^1.8.5
  device_info_plus: ^10.1.2
  diacritic: ^0.1.3
  dio: ^5.4.0
  file: ^7.0.0
  firebase_crashlytics: ^4.3.10
  firebase_performance: ^0.10.1+5
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_messaging: ^15.2.5
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.0.2
  flutter_highlight: ^0.7.0
  flutter_html: ^3.0.0-beta.2
  flutter_markdown: ^0.7.3+1
  flutter_riverpod: ^2.0.0-dev.4
  flutter_sticky_header: ^0.6.0
  fluttertoast: ^8.0.9
  google_fonts: ^6.1.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  html: ^0.15.0
  html_unescape: ^2.0.0
  http: ^1.2.0
  image: ^4.1.7
  image_picker: ^1.0.7
  material_design_icons_flutter: ^7.0.7296
  meta: ^1.7.0
  package_info_plus: ^8.0.2
  path: ^1.8.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1
  photo_view: ^0.14.0
  provider: ^6.0.2
  scroll_to_index: any
  settings_ui: ^2.0.2
  share_plus: ^7.2.2
  shared_preferences: ^2.0.13
  tap_canvas: ^0.9.4
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  webview_flutter: ^4.10.0

  # Dart-lang core plugins ðŸ‘‡
  http_parser: ^4.0.0
  mime: ^1.0.1
  intl: ^0.18.1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  modal_bottom_sheet:
    git:
      url: https://github.com/eli1stark/modal_bottom_sheet.git
      ref: 2b3f9f84f46418c1b337968c88883995f65f47e7
      path: modal_bottom_sheet
  quiver: ^3.2.1
  markdown: ^7.2.2
  gallery_saver_plus: ^3.2.8
  pasteboard: ^0.4.0
  supabase_flutter: ^2.10.3
  flutter_it: ^2.1.1

dependency_overrides:
  intl: any
  # https://claude.ai/share/ec339603-37b2-4a49-8ffc-b78266063879
  app_links: 6.3.0

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.14.3
  analyzer: ^6.2.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  image_path_ios_dark_transparent: "assets/app_icon-transparent.png"
  remove_alpha_ios: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/logo.png
    - assets/tutorial-1.png
    - assets/tutorial-2.png
    - assets/tutorial-3.png
    - assets/tutorial-4.png
    - assets/travolta.gif
    - assets/philosoraptor.png
    - assets/lets-encrypt-r3.cer
    - assets/inter_font/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/JetBrainsMono-SemiLight.ttf
