name: fyx
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.9.0+71

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.5

dependencies:
  provider: ^6.0.2
  meta: ^1.7.0
  dio: ^4.0.3
  flutter_sticky_header: ^0.6.0
  html: ^0.15.0
  flutter_html: ^2.2.1
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  html_unescape: ^2.0.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  device_info: ^2.0.3
  package_info: ^2.0.2
  url_launcher: ^6.1.5
  photo_view: ^0.13.0
  auto_size_text: ^3.0.0-nullsafety.0
  image_picker: ^0.8.4+10
  path: ^1.8.0
  image: ^3.1.3
  async: ^2.8.2
  chewie: ^1.3.0
  video_player: ^2.2.19
  settings_ui: ^2.0.2
  flutter_markdown: ^0.6.9
  http: ^0.13.4
  share: ^2.0.4
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  firebase_analytics: ^8.3.4
  sentry_flutter: ^6.9.1
  flutter_dotenv: ^5.0.2
  firebase_messaging: ^11.1.0
  flutter_highlight: ^0.7.0
  image_gallery_saver: ^1.7.1
  path_provider: 2.0.9
  permission_handler: 9.2.0
  scroll_to_index: any
  flutter_riverpod: ^2.0.0-dev.4
  diacritic: ^0.1.3
  tap_canvas: ^0.9.4
  webview_flutter: ^2.0.4
  google_fonts: ^3.0.1
  material_design_icons_flutter: 5.0.6996

  # Dart-lang core plugins ðŸ‘‡
  http_parser: ^4.0.0
  mime: ^1.0.1
  intl: ^0.17.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dependency_overrides:
#  # https://github.com/flutter/flutter/issues/44435#issuecomment-817583694
#  webview_flutter: ^2.0.10
#  package_info_plus: ^1.3.0

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.9.3
  analyzer: ^4.6.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - logo.png
    - tutorial-1.png
    - tutorial-2.png
    - tutorial-3.png
    - tutorial-4.png
    - travolta.gif
    - lets-encrypt-r3.cer
    - assets/inter_font/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/JetBrainsMono-SemiLight.ttf
